server:
  port: 8081

accounts:
  services:
    external:
      url:  https://api.coinlore.net/api/ticker
#      retrieving:
#        fixed-delay: PT60
#        initial-delay: PT10
#      checking:
#        fixed-delay: 60
#        initial-delay: 15

spring:
  application:
    name:  accountsREST

  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username:  accounts
    password:  accounts
    driverClassName: org.postgresql.Driver

  flyway:
    schemas:
      - public
      - accounts

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
#    show-sql: true

