server:
  port: 8081

spring:
  application:
    name:  accountsREST

  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username:  accounts
    password:  accounts
    driverClassName: org.postgresql.Driver

  flyway:
    schemas:
      - public
      - accounts

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

